---
id: nacl79
base_name: memo_meeting
tags: []
presentation_date: 2014-08-25
version: 2014.08.25.1
licenses:
- CC BY 2.1 JP
slideshare_id: 
speaker_deck_id: meeting-about-memo
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Yuya.Nishida.
  email: yuyaAT@ATj96DOT.DOTorg
  rubygems_user: nishidayuya
  slideshare_user: 
  speaker_deck_user: nishidayuya
